using System;

namespace EVE.ISXEVE.Enums
{
	/// <summary>
	/// Enumeration for group ID's
	/// </summary>
	public enum Group
	{
		None = -1,
		System,
		Character,
		Corporation,
		Region,
		Constellation,
		SolarSystem,
		Sun,
		Planet,
		Moon,
		AsteroidBelt,
		Stargate,
		AsteroidOLD,
		CargoContainer,
		Ring,
		Biomass,
		Station,
		StationServices,
		Money,
		Mineral,
		Faction,
		Drug,
		Clone = 23,
		Voucher,
		Frigate,
		Cruiser,
		Battleship,
		Industrial,
		Capsule,
		Titan,
		Shuttle,
		Alliance,
		ShieldExtender = 38,
		ShieldRecharger,
		ShieldBooster,
		RemoteShieldBooster,
		CapacitorRecharger = 43,
		PropulsionModule = 46,
		CargoScanner,
		ShipScanner,
		SurveyScanner,
		WarpScrambler = 52,
		EnergyWeapon,
		MiningLaser,
		ProjectileWeapon,
		MissileLauncher,
		ShieldPowerRelay,
		Gyrostabilizer = 59,
		DamageControl,
		CapacitorBattery,
		ArmorRepairUnit,
		HullRepairUnit,
		StasisWeb = 65,
		RemoteCapacitorTransmitter = 67,
		EnergyNosferatu,
		EnergyNeutralizer = 71,
		SmartBomb,
		HybridWeapon = 74,
		CapacitorBooster = 76,
		ShieldHardener,
		ReinforcedBulkhead,
		BurstJammer = 80,
		PassiveTargetingSystem = 82,
		ProjectileAmmo,
		HybridCharge = 85,
		FrequencyCrystal,
		CapacitorBoosterCharge,
		LightDefenderMissile,
		Torpedo,
		Bomb,
		Mine = 92,
		Trading = 94,
		TradeSession,
		AutomatedTargetingSystem,
		ProximityDrone,
		ArmorCoating,
		SentryGun,
		CombatDrone,
		MiningDrone,
		CloneBlueprint = 104,
		FrigateBlueprint,
		CruiserBlueprint,
		BattleshipBlueprint,
		IndustrialBlueprint,
		CapsuleBlueprint,
		TitanBlueprint,
		ShuttleBlueprint,
		ShieldExtenderBlueprint = 118,
		ShieldRechargerBlueprint,
		ShieldBoosterBlueprint,
		RemoteShieldBoosterBlueprint,
		CapacitorRechargerBlueprint = 123,
		PropulsionModuleBlueprint = 126,
		CargoScannerBlueprint,
		ShipScannerBlueprint,
		SurveyScannerBlueprint,
		ECMBlueprint,
		ECCMBlueprint,
		WarpScramblerBlueprint,
		EnergyWeaponBlueprint,
		MiningLaserBlueprint,
		ProjectileWeaponBlueprint,
		MissileLauncherBlueprint,
		PowerManagerBlueprint,
		GunneryUpgradeBlueprint = 139,
		DamageControlBlueprint,
		CapacitorBatteryBlueprint,
		ArmorRepairUnitBlueprint,
		HullRepairUnitBlueprint,
		StasisWebBlueprint = 145,
		RemoteCapacitorTransmitterBlueprint = 147,
		EnergyNosferatuBlueprint,
		EnergyNeutralizerBlueprint = 151,
		SmartBombBlueprint,
		HybridWeaponBlueprint = 154,
		CapacitorBoosterBlueprint = 156,
		ShieldHardenerBlueprint,
		HullModsBlueprint,
		BurstJammerBlueprint = 160,
		PassiveTargetingSystemBlueprint,
		AutomatedTargetingSystemBlueprint,
		ArmorCoatingBlueprint,
		ProjectileAmmoBlueprint = 165,
		MissileBlueprint,
		HybridChargeBlueprint,
		FrequencyCrystalBlueprint,
		CapacitorBoosterChargeBlueprint,
		DefenderMissileBlueprint,
		BombBlueprint = 172,
		MineBlueprint = 174,
		ProximityDroneBlueprint,
		CombatDroneBlueprint,
		MiningDroneBlueprint,
		DrugBlueprint,
		ProtectiveSentryGun = 180,
		PoliceDrone = 182,
		PirateDrone = 185,
		Wreck,
		BloodlineBonus = 190,
		PhysicalBenefit,
		PhysicalHandicap,
		PhobiaHandicap,
		SocialHandicap,
		AmarrEducation,
		CaldariEducation,
		GallenteEducation,
		MinmatarEducation,
		CareerBonus,
		ECM = 201,
		ECCM,
		SensorBackupArray,
		HeatSink = 205,
		SensorDampener = 208,
		RemoteTrackingComputer,
		SignalAmplifier,
		TrackingEnhancer,
		SensorBooster,
		TrackingComputer,
		HeatSinkBlueprint = 218,
		SensorBoosterBlueprint = 223,
		TrackingComputerBlueprint,
		CheatModuleGroup,
		LargeCollidableObject,
		Cloud,
		Rookieship = 237,
		Gunnery = 255,
		Missiles,
		SpaceshipCommand,
		Leadership,
		CorporationManagement = 266,
		ObsoleteBooks,
		Production,
		Rigging,
		Science,
		ElectronicSystems = 272,
		Drones,
		Trade,
		Navigation,
		Social = 278,
		LCODrone,
		General,
		Frozen,
		Radioactive,
		Livestock,
		Biohazard,
		CPUEnhancer,
		MinorThreat,
		RogueDrone,
		FactionDrone,
		ProjectedECCM,
		RemoteSensorBooster,
		WeaponDisruptor,
		ShieldAmplifier = 295,
		ShieldAmplifierBlueprint,
		Convoy,
		ConvoyDrone,
		RepairDrone,
		Cyberimplant,
		ConcordDrone,
		MagneticFieldStabilizer,
		Booster,
		DNAMutator,
		Comet,
		SpawnContainer,
		ConstructionPlatform,
		CountermeasureLauncher,
		Autopilot,
		Beacon,
		ReprocessingArray,
		PlanetaryCloud,
		Drugs,
		Miscellaneous,
		WarpCoreStabilizer,
		GangCoordinator,
		ComputerInterfaceNode,
		Landmark,
		LargeCollidableStructure,
		ShieldDisruptor = 321,
		Billboard = 323,
		AssaultFrigate,
		RemoteArmorRepairer,
		ArmorPlatingEnergized,
		ArmorHardener = 328,
		ArmorReinforcer,
		CloakingDevice,
		Tool = 332,
		Datacores,
		ConstructionComponents,
		TemporaryCloud,
		MobileSentryGun,
		MissionDrone,
		ShieldBoostAmplifier,
		AuxiliaryPowerCore,
		SecureCargoContainer,
		SignatureScrambling,
		AntiWarpScramblerBlueprint,
		WeaponDisruptorBlueprint,
		TrackingEnhancerBlueprint,
		RemoteTrackingComputerBlueprint,
		CoProcessorBlueprint,
		SignalAmplifierBlueprint,
		ArmorHardenerBlueprint,
		ArmorReinforcerBlueprint,
		RemoteArmorRepairerBlueprint,
		AuxiliaryPowerCoreBlueprint = 352,
		QAModule,
		Refinables = 355,
		ToolBlueprint,
		DroneBayExpander,
		HeavyAssaultCruiser,
		ShieldBoostAmplifierBlueprint = 360,
		MobileWarpDisruptor,
		ShipMaintenanceArray = 363,
		MobileStorage,
		ControlTower,
		WarpGate,
		BallisticControlsystem,
		GlobalWarpDisruptor,
		ShipLogs,
		CriminalTags,
		MobileWarpDisruptorBlueprint,
		AdvancedAutocannonAmmo,
		AdvancedRailgunCharge,
		AdvancedBeamLaserCrystal,
		AdvancedPulseLaserCrystal,
		AdvancedArtilleryAmmo,
		AdvancedBlasterCharge,
		CruiseControl,
		TargetPainter,
		DeepSpaceTransport,
		EliteBattleship,
		ShippingCrates,
		DestructibleSentryGun,
		LightMissile,
		HeavyMissile,
		CruiseMissile,
		Rocket,
		FoFLightMissile = 394,
		FoFHeavyMissile,
		FoFCruiseMissile,
		AssemblyArray,
		BallisticControlSystemBlueprint = 400,
		CloakingDeviceBlueprint,
		Silo = 404,
		AntiCloakingPulse,
		SmartbombSupercharger,
		DroneControlUnit,
		DroneUpgradeBlueprint,
		EmpireInsigniaDrops,
		AntiCloakingPulseBlueprint,
		ForceField,
		Laboratory = 413,
		MobilePowerCore,
		MoonMining = 416,
		MobileMissileSentry,
		MobileShieldGenerator,
		CombatBattlecruiser,
		Destroyer,
		GasIsotopes = 422,
		IceProduct,
		OrbitalAssaultUnit = 425,
		MobileProjectileSentry,
		MoonMaterials,
		IntermediateMaterials,
		Composite,
		MobileLaserSentry,
		DeadspaceOverseer = 435,
		SimpleReaction,
		MobileReactor = 438,
		ElectronicWarfareBattery,
		SensorDampeningBattery,
		StasisWebificationBattery,
		WarpScramblingBattery = 443,
		ShieldHardeningArray,
		ForceFieldArray,
		CustomsOfficial,
		ConstructionComponentBlueprints,
		AuditLogSecureContainer,
		MobileHybridSentry,
		Arkonor,
		Bistot,
		Crokite,
		DarkOchre,
		Hedbergite,
		Hemorphite,
		Jaspet,
		Kernite,
		Plagioclase,
		Pyroxeres,
		Scordite,
		Spodumain,
		Veldspar,
		MiningBarge,
		StripMiner,
		Ice,
		Gneiss = 467,
		Mercoxit,
		Omber,
		UnanchoringDrone,
		CorporateHangarArray,
		SystemScanner,
		TrackingArray,
		AccelerationGateKeys,
		Microwarpdrive,
		CapitalTorpedo,
		MiningBargeBlueprint,
		SystemScannerBlueprint,
		ScannerProbe,
		StealthEmitterArray,
		ScanProbeLauncher,
		MiningCrystal,
		FrequencyMiningLaser,
		ComplexReactions,
		Dreadnought,
		ScanProbeBlueprint,
		DestroyerBlueprint,
		BattlecruiserBlueprint = 489,
		StripMinerBlueprint,
		SurveyProbe = 492,
		OverseerPersonalEffects,
		DeadspaceOverseersStructure,
		DeadspaceOverseersSentry,
		DeadspaceOverseersBelongings,
		Fuel,
		Modifications,
		NewEWTesting,
		FestivalCharges,
		FestivalLauncher,
		CosmicSignature,
		EliteIndustrialBlueprint,
		TargetPainterBlueprint,
		FakeSkills,
		MissileLauncherCruise,
		MissileLauncherRocket,
		MissileLauncherTorpedo,
		MissileLauncherLight,
		MissileLauncherHeavy,
		MissileLauncherRapidLight,
		MissileLauncherDefender,
		Freighter,
		ECMStabilizer,
		SiegeModule,
		SiegeModuleBlueprint,
		AgentsinSpace,
		AntiBallisticDefenseSystem,
		TerranArtifacts,
		StorylineFrigate,
		Identification,
		StorylineCruiser,
		StorylineBattleship,
		XLMissileLauncher,
		FreighterBlueprint,
		Commodities,
		StorylineMissionFrigate,
		ArtifactsandPrototypes,
		MaterialsandCompounds = 530,
		GangCoordinatorBlueprint = 532,
		StorylineMissionCruiser,
		StorylineMissionBattleship,
		ConstructionPlatformBlueprint,
		StationComponents,
		DreadnoughtBlueprint,
		DataMiners,
		CommandShip = 540,
		Interdictor,
		Exhumer = 543,
		EnergyNeutralizerDrone,
		WarpScramblingDrone,
		MiningUpgrade,
		Carrier,
		InterdictionProbe,
		FighterDrone,
		AsteroidAngelCartelFrigate,
		AsteroidAngelCartelCruiser,
		AsteroidAngelCartelBattleship,
		AsteroidAngelCartelOfficer,
		AsteroidAngelCartelHauler,
		AsteroidBloodRaidersCruiser,
		AsteroidBloodRaidersBattleship,
		AsteroidBloodRaidersFrigate,
		AsteroidBloodRaidersHauler,
		AsteroidBloodRaidersOfficer,
		AsteroidGuristasBattleship,
		AsteroidGuristasCruiser,
		AsteroidGuristasFrigate,
		AsteroidGuristasHauler,
		AsteroidGuristasOfficer,
		AsteroidSanshasNationBattleship,
		AsteroidSanshasNationCruiser,
		AsteroidSanshasNationFrigate,
		AsteroidSanshasNationHauler,
		AsteroidSanshasNationOfficer,
		AsteroidSerpentisBattleship,
		AsteroidSerpentisCruiser,
		AsteroidSerpentisFrigate,
		AsteroidSerpentisHauler,
		AsteroidSerpentisOfficer,
		AsteroidAngelCartelDestroyer,
		AsteroidAngelCartelBattleCruiser,
		AsteroidBloodRaidersDestroyer,
		AsteroidBloodRaidersBattleCruiser,
		AsteroidGuristasDestroyer,
		AsteroidGuristasBattleCruiser,
		AsteroidSanshasNationDestroyer,
		AsteroidSanshasNationBattleCruiser,
		AsteroidSerpentisDestroyer,
		AsteroidSerpentisBattleCruiser,
		RemoteHullRepairer,
		DroneModules,
		SuperWeapon = 588,
		InterdictionSphereLauncher,
		JumpPortalGenerator,
		DeadspaceAngelCartelBattleCruiser = 593,
		DeadspaceAngelCartelBattleship,
		DeadspaceAngelCartelCruiser,
		DeadspaceAngelCartelDestroyer,
		DeadspaceAngelCartelFrigate,
		DeadspaceBloodRaidersBattleCruiser = 602,
		DeadspaceBloodRaidersBattleship,
		DeadspaceBloodRaidersCruiser,
		DeadspaceBloodRaidersDestroyer,
		DeadspaceBloodRaidersFrigate,
		DeadspaceGuristasBattleCruiser = 611,
		DeadspaceGuristasBattleship,
		DeadspaceGuristasCruiser,
		DeadspaceGuristasDestroyer,
		DeadspaceGuristasFrigate,
		DeadspaceSanshasNationBattleCruiser = 620,
		DeadspaceSanshasNationBattleship,
		DeadspaceSanshasNationCruiser,
		DeadspaceSanshasNationDestroyer,
		DeadspaceSanshasNationFrigate,
		DeadspaceSerpentisBattleCruiser = 629,
		DeadspaceSerpentisBattleship,
		DeadspaceSerpentisCruiser,
		DeadspaceSerpentisDestroyer,
		DeadspaceSerpentisFrigate,
		NavigationComputer = 638,
		ElectronicWarfareDrone,
		LogisticDrone,
		StasisWebifyingDrone,
		SuperGangEnhancer,
		CarrierBlueprint,
		DroneNavigationComputer,
		DroneDamageModules,
		DroneTrackingModules,
		DroneControlRangeModule,
		AdvancedRocket,
		FreightContainer,
		TractorBeam,
		SuperWeaponBlueprint,
		Lease,
		AdvancedLightMissile,
		AdvancedHeavyAssaultMissile,
		AdvancedHeavyMissile,
		AdvancedCruiseMissile,
		AdvancedTorpedo,
		CynosuralField,
		Supercarrier,
		EnergyVampireSlayer,
		SimpleBiochemicalReactions,
		ComplexBiochemicalReactions,
		MercoxitMiningCrystal,
		MissionAmarrEmpireFrigate = 665,
		MissionAmarrEmpireBattlecruiser,
		MissionAmarrEmpireBattleship,
		MissionAmarrEmpireCruiser,
		MissionAmarrEmpireDestroyer,
		MissionAmarrEmpireOther,
		MissionCaldariStateFrigate,
		MissionCaldariStateBattlecruiser,
		MissionCaldariStateCruiser,
		MissionCaldariStateBattleship,
		MissionCaldariStateOther,
		MissionCaldariStateDestroyer,
		MissionGallenteFederationFrigate,
		MissionGallenteFederationCruiser,
		MissionGallenteFederationDestroyer,
		MissionGallenteFederationBattleship,
		MissionGallenteFederationBattlecruiser,
		MissionGallenteFederationOther,
		MissionMinmatarRepublicFrigate,
		MissionMinmatarRepublicDestroyer,
		MissionMinmatarRepublicBattlecruiser,
		MissionMinmatarRepublicOther,
		MissionKhanidFrigate,
		MissionKhanidDestroyer,
		MissionKhanidCruiser,
		MissionKhanidBattlecruiser,
		MissionKhanidBattleship,
		MissionKhanidOther,
		MissionCONCORDFrigate,
		MissionCONCORDDestroyer,
		MissionCONCORDCruiser,
		MissionCONCORDBattlecruiser,
		MissionCONCORDBattleship,
		MissionCONCORDOther,
		MissionMorduFrigate,
		MissionMorduDestroyer,
		MissionMorduCruiser,
		MissionMorduBattlecruiser,
		MissionMorduBattleship,
		MissionMorduOther,
		MissionMinmatarRepublicCruiser,
		MissionMinmatarRepublicBattleship,
		JumpPortalArray,
		ScannerArray = 709,
		LogisticsArray,
		HarvestableCloud,
		BiochemicalMaterial,
		DestructibleAgentsInSpace = 715,
		DataInterfaces,
		BoosterBlueprints = 718,
		Temp = 721,
		AdvancedHybridChargeBlueprint,
		TractorBeamBlueprint,
		ImplantBlueprints,
		AdvancedProjectileAmmoBlueprint,
		AdvancedFrequencyCrystalBlueprint,
		MiningCrystalBlueprint,
		DecryptorsAmarr,
		DecryptorsMinmatar,
		DecryptorsGallente,
		DecryptorsCaldari,
		DecryptorsSleepers,
		DecryptorsYanJung,
		DecryptorsTakmahl,
		DecryptorsTalocan,
		GasCloudHarvester = 737,
		CyberArmor,
		CyberDrones,
		CyberElectronicSystems,
		CyberEngineering,
		CyberGunnery,
		CyberProduction,
		CyberLeadership,
		CyberLearning,
		CyberMissile,
		CyberNavigation,
		CyberScience,
		CyberShields,
		CyberSocial,
		CyberTrade,
		ECMEnhancer = 753,
		SalvagedMaterials,
		AsteroidRogueDroneBattleCruiser,
		AsteroidRogueDroneBattleship,
		AsteroidRogueDroneCruiser,
		AsteroidRogueDroneDestroyer,
		AsteroidRogueDroneFrigate,
		AsteroidRogueDroneHauler,
		AsteroidRogueDroneSwarm,
		InertialStabilizer,
		NanofiberInternalStructure,
		OverdriveInjectorSystem,
		ExpandedCargohold,
		PowerDiagnosticSystem,
		CapacitorPowerRelay,
		CapacitorFluxCoil,
		ReactorControlUnit,
		ShieldFluxCoil,
		MissileLauncherHeavyAssault,
		HeavyAssaultMissile,
		RigArmor,
		RigShield,
		RigEnergyWeapon,
		RigHybridWeapon,
		RigProjectileWeapon,
		RigDrones,
		RigLauncher,
		RigCore = 781,
		RigNavigation,
		CyberXSpecials,
		LargeCollidableShip,
		RigElectronicSystems = 786,
		RigBlueprint,
		AsteroidAngelCartelCommanderFrigate = 789,
		AsteroidAngelCartelCommanderCruiser,
		AsteroidBloodRaidersCommanderCruiser,
		AsteroidBloodRaidersCommanderFrigate,
		AsteroidAngelCartelCommanderBattleCruiser,
		AsteroidAngelCartelCommanderDestroyer,
		AsteroidBloodRaidersCommanderBattleCruiser,
		AsteroidBloodRaidersCommanderDestroyer,
		AsteroidGuristasCommanderBattleCruiser,
		AsteroidGuristasCommanderCruiser,
		AsteroidGuristasCommanderDestroyer,
		AsteroidGuristasCommanderFrigate,
		DeadspaceRogueDroneBattleCruiser,
		DeadspaceRogueDroneBattleship,
		DeadspaceRogueDroneCruiser,
		DeadspaceRogueDroneDestroyer,
		DeadspaceRogueDroneFrigate,
		DeadspaceRogueDroneSwarm,
		AsteroidSanshasNationCommanderBattleCruiser,
		AsteroidSanshasNationCommanderCruiser,
		AsteroidSanshasNationCommanderDestroyer,
		AsteroidSanshasNationCommanderFrigate,
		AsteroidSerpentisCommanderBattleCruiser,
		AsteroidSerpentisCommanderCruiser,
		AsteroidSerpentisCommanderDestroyer,
		AsteroidSerpentisCommanderFrigate,
		CloneVatBay,
		MissionGenericBattleships,
		MissionGenericCruisers,
		MissionGenericFrigates,
		DeadspaceOverseerFrigate,
		DeadspaceOverseerCruiser,
		DeadspaceOverseerBattleship,
		MissionThukkerBattlecruiser,
		MissionThukkerBattleship,
		MissionThukkerCruiser,
		MissionThukkerDestroyer,
		MissionThukkerFrigate,
		MissionThukkerOther,
		MissionGenericBattleCruisers,
		MissionGenericDestroyers,
		CovertOps,
		Interceptor,
		Logistics,
		ForceReconShip,
		StealthBomber,
		StationUpgradePlatform,
		StationImprovementPlatform,
		EnergyNeutralizingBattery,
		CynosuralGeneratorArray,
		CynosuralSystemJammer,
		StructureRepairArray,
		StarbaseControlTowerBlueprints,
		RemoteECMBurst,
		AsteroidRogueDroneCommanderBattleCruiser,
		AsteroidRogueDroneCommanderBattleship,
		AsteroidRogueDroneCommanderCruiser,
		AsteroidRogueDroneCommanderDestroyer,
		AsteroidRogueDroneCommanderFrigate,
		AsteroidAngelCartelCommanderBattleship,
		AsteroidBloodRaidersCommanderBattleship,
		AsteroidGuristasCommanderBattleship,
		AsteroidSanshasNationCommanderBattleship,
		AsteroidSerpentisCommanderBattleship,
		StarbaseLaserBatteryBlueprints,
		StarbaseProjectileBatteryBlueprints,
		StarbaseHybridBatteryBlueprints,
		StarbaseECMJammingArrayBlueprints,
		StarbaseWarpScramblingBatteryBlueprints,
		StarbaseStasisWebificationBatteryBlueprints,
		StarbaseSensorDampeningArrayBlueprints,
		StarbaseEnergyNeutralizingBatteryBlueprints,
		MissionFighterDrone,
		MissileLauncherBomb,
		BombECM,
		BombEnergy,
		MissionAmarrEmpireCarrier,
		MissionCaldariStateCarrier,
		MissionGallenteFederationCarrier,
		MissionMinmatarRepublicCarrier,
		RemoteHullRepairerBlueprint = 870,
		StarbaseMissileBatteryBlueprints,
		OutpostImprovements,
		CapitalConstructionComponents,
		DisruptableStationServices,
		MissionFactionTransports,
		OutpostUpgrades,
		TargetPaintingBattery,
		CloakEnhancements,
		SlaveReception,
		SleeperComponents,
		FreedomPrograms,
		EnslavementPrograms,
		CapitalIndustrialShip,
		TestCompressedOre,
		CosmicAnomaly,
		RogueDroneComponents,
		OreCompressionBlueprints = 888,
		OreEnhancementBlueprints,
		IceCompressionBlueprints,
		StarbaseMobileLaboratoryBlueprints,
		PlanetSatellites,
		ElectronicAttackShip,
		HeavyInterdictionCruiser,
		RigSecurityTransponder = 896,
		CovertBeacon,
		BlackOps,
		WarpDisruptFieldGenerator,
		Marauder,
		MiningEnhancer,
		JumpFreighter,
		AncientCompressedIce,
		RigMining,
		CovertCynosuralFieldGenerator,
		CombatReconShip,
		TrackingScript,
		WarpDisruptionScript,
		TrackingDisruptionScript,
		SensorBoosterScript,
		SensorDampenerScript,
		ScriptBlueprint,
		AdvancedCapitalConstructionComponents,
		AdvancedCapitalConstructionComponentBlueprints,
		CapitalConstructionBlueprints,
		NaniteRepairPaste,
		DataMinerBlueprint,
		ScanProbeLauncherBlueprint,
		EffectBeacon = 920,
		CapturePoint = 922,
		MissionFactionBattleship = 924,
		FWInfrastructureHub,
		MissionFactionIndustrials = 927,
		ZombieEntities = 934,
		WorldSpace,
		Decorations = 937,
		Furniture = 940,
		IndustrialCommandShip,
		GameTime = 943,
		CapitalIndustrialShipBlueprint,
		IndustrialCommandShipBlueprint,
		MissionContainer = 952,
		DefensiveSystems = 954,
		ElectronicSystems1,
		OffensiveSystems,
		PropulsionSystems,
		EngineeringSystems,
		DeadspaceSleeperSleeplessSentinel,
		DeadspaceSleeperAwakenedSentinel,
		DeadspaceSleeperEmergentSentinel,
		StrategicCruiser = 963,
		HybridTechComponents,
		HybridComponentBlueprints,
		AncientSalvage,
		WormholeMinerals,
		SleeperPropulsionRelics = 971,
		ObsoleteProbes,
		SubsystemBlueprints,
		HybridPolymers,
		FestivalChargesExpired = 976,
		HybridReactions,
		DecryptorsHybrid = 979,
		DeadspaceSleeperSleeplessDefender = 982,
		DeadspaceSleeperSleeplessPatroller,
		DeadspaceSleeperAwakenedDefender,
		DeadspaceSleeperAwakenedPatroller,
		DeadspaceSleeperEmergentDefender,
		DeadspaceSleeperEmergentPatroller,
		Wormhole,
		SleeperElectronicsRelics = 990,
		SleeperOffensiveRelics,
		SleeperEngineeringRelics,
		SleeperDefensiveRelics,
		SecondarySun = 995,
		StrategicCruiserBlueprints,
		SleeperHullRelics,
		TerritorialClaimUnit = 1003,
		DefenseBunkers,
		SovereigntyBlockadeUnit,
		MissionFactionCruiser,
		MissionFactionFrigate,
		CompactXLTorpedo = 1010,
		InfrastructureHub = 1012,
		SupercarrierBlueprints,
		StrategicUpgrades = 1016,
		CapitalCruise = 1019,
		IndustrialUpgrades,
		MilitaryUpgrades,
		PrototypeExplorationShip,
		FighterBomber,
		OrbitalInfrastructure = 1025,
		Extractors,
		CommandCenters,
		Processors,
		StorageFacilities,
		Spaceports,
		PlanetaryResources,
		PlanetSolid,
		PlanetLiquidGas,
		RefinedCommodities,
		PlanetOrganic,
		PlanetaryLinks,
		SpecializedCommodities = 1040,
		AdvancedCommodities,
		BasicCommodities,
		SovereigntyStructureBlueprint = 1045,
		NaniteRepairPasteBlueprint,
		StarbaseBlueprint = 1048,
		IncursionSanshasNationIndustrial = 1051,
		IncursionSanshasNationCapital,
		IncursionSanshasNationFrigate,
		IncursionSanshasNationCruiser,
		IncursionSanshasNationBattleship = 1056,
		ExtractorControlUnits = 1063,
		MaterialZone = 1067,
		DetailMesh,
		Flashpoint = 1071,
		TestOrbitals = 1073,
		Generic = 1079,
		MercenaryBases = 1081,
		CapsuleerBases,
		Eyewear,
		Tattoos,
		Piercings,
		Scars,
		MidLayer,
		Outer,
		Tops,
		Bottoms,
		Footwear,
		HairStyles,
		Makeup,
		LensFlares = 1105,
		OrbitalConstructionPlatform,
		ParticleSystems,
		AnimatedLights,
		Audio,
		PointLights,
		BoxLights,
		SpotLights,
		SurfaceInfrastructurePrefabUnits = 1118,
		PerceptionPoints = 1121,
		Salvager,
		SalvagerBlueprint,
		PhysicalPortals = 1126,
		FuelBlock = 1136,
		FuelBlockBlueprint,
		MiningLaserUpgradeBlueprint = 1139,
		ResearchData = 1141,
		EnergyNeutralizerDroneBlueprint,
		ElectronicWarfareDroneBlueprint,
		LogisticDroneBlueprint,
		FighterBomberBlueprint,
		FighterDroneBlueprint,
		StasisWebifyingDroneBlueprint,
		MobileJumpDisruptor = 1149,
		ArmorResistanceShiftHardener,
		ArmorResistanceShiftHardenerBlueprint,
		DroneDamageModuleBlueprint,
		ShieldBoosterScript,
		TargetBreaker,
		TargetBreakerBlueprint,
		FueledShieldBooster,
		FueledShieldBoosterBlueprint,
		HeavyDefenderMissile,
		SalvageDrone,
		SurveyProbeBlueprints,
		ContainerBlueprints = 1162,
		Satellite = 1165,
		FWMinmatarRepublicFrigate,
		FWCaldariStateFrigate,
		FWGallenteFederationFrigate,
		FWAmarrEmpireFrigate,
		AsteroidRogueDroneOfficer = 1174,
		FWAmarrEmpireDestroyer,
		FWCaldariStateDestroyer,
		FWGallenteFederationDestroyer,
		FWMinmatarRepublicDestroyer,
		FWAmarrEmpireCruiser,
		FWCaldariStateCruiser,
		FWGallenteFederationCruiser,
		FWMinmatarRepublicCruiser,
		FWAmarrEmpireBattlecruiser,
		FWCaldariStateBattlecruiser,
		FWGallenteFederationBattlecruiser,
		FWMinmatarRepublicBattlecruiser,
		MicroJumpDrive = 1189,
		SalvageDroneBlueprint,
		MicroJumpDriveBlueprint,
		SpecialEditionCommodities = 1194,
		SpecialEditionCommodityBlueprints = 1197,
		OrbitalTarget,
		FueledArmorRepairer,
		FueledArmorRepairerBlueprint,
		AttackBattlecruiser,
		BlockadeRunner,
		SecurityTags = 1206,
		ScatterContainer,
		Shields = 1209,
		Armor,
		PersonalHangar = 1212,
		Targeting,
		Engineering = 1216,
		Scanning,
		ResourceProcessing,
		NeuralEnhancement = 1220,
		ECMStabilizerBlueprint = 1222,
		ScanningUpgrade,
		ScanningUpgradeBlueprint,
		SurveyProbeLauncher = 1226,
		SurveyProbeLauncherBlueprint,
		CyberTargeting,
		CyberResourceProcessing,
		CyberScanning,
		CyberBiology,
		RigResourceProcessing,
		RigScanning,
		RigTargeting,
		ScanningUpgradeTime = 1238,
		ScanningUpgradeTimeBlueprint,
		Subsystems,
		PlanetManagement,
		MissileLauncherRapidHeavy = 1245,
		MobileDepot,
		MobileSiphonUnit,
		EmpireBountyReimbursementTags,
		MobileCynoInhibitor,
		MobileTractorUnit,
		GhostSitesAngelCartelCruiser = 1252,
		GhostSitesBloodRaidersCruiser = 1255,
		GhostSitesGuristasCruiser = 1259,
		GhostSitesSerpentisCruiser = 1262,
		GhostSitesSanshasCruiser = 1265,
		MobileSiphonUnitBlueprint = 1267,
		MobileCynosuralInhibitorBlueprint,
		MobileDepotBlueprint,
		MobileTractorUnitBlueprint,
		Prosthetics,
		EncounterSurveillanceSystem = 1273,
		MobileDecoyUnit,
		MobileScanInhibitor,
		MobileMicroJumpUnit,
		EncounterSurveillanceSystemBlueprint,
		CompressionArray = 1282,
		ExpeditionFrigate,
		AsteroidMordusLegionCommanderFrigate = 1285,
		AsteroidMordusLegionCommanderCruiser,
		AsteroidMordusLegionCommanderBattleship,
		GhostSitesMordusLegion,
		WarpAccelerator,
		DroneTrackingEnhancer = 1292,
		MobileScanInhibitorBlueprint,
		MobileMicroJumpUnitBlueprint,
		MobileDecoyUnitBlueprint,
		MobileVault = 1297,
		JumpDriveEconomizer = 1299,
		Services = 1301,
		GenericDecryptor = 1304,
		TacticalDestroyer,
		ShipModifiers,
		RoamingSleepersCruiser,
		RigAnchor,
		TacticalDestroyerBlueprint,
		DrifterBattleship,
		SuperKerrInducedNanocoatings,
		ObservatoryStructures,
		EntosisLink,
		UnknownComponents,
		EntosisCommandNode = 1316,
		InfrastructureUpgradeBlueprint,
		EntosisLinkBlueprint,
		Miscellaneous1,
		XLargeCitadel,
		StructureCitadelServiceModule,
		StructureDrillingServiceModule,
		StructureObservatoryServiceModule,
		StructureStargateServiceModule,
		StructureAdministrationServiceModule,
		StructureAdvertisementServiceModule,
		StructureAntiShipLauncher,
		StructureAoEMissileLauncher,
		StructureEnergyNeutralizer,
		StructureDefenseBattery,
		StructureBumpingModule,
		StructureECM,
		StructureDoomsdayWeapon,
		MissileGuidanceEnhancer = 1395,
		MissileGuidanceComputer,
		MissileGuidanceEnhancerBlueprint,
		MissileGuidanceComputerBlueprint = 1399,
		MissileGuidanceScript,
		AmarrNavyRoamingBattleship = 1402,
		AssemblyArray1 = 1404,
		Laboratory1,
		DrillingPlatform,
		ObservatoryArray,
		Stargate1,
		AdministrationHub,
		AdvertisementCenter,
		AmarrNavyRoamingCruiser,
		AmarrNavyRoamingCapital,
		AmarrNavyRoamingLogistics,
		AmarrNavyRoamingFrigate,
		StructureAssemblyServiceModule,
		StructureResearchServiceModule,
		StructureWarfareLink = 1418,
		StructureRemoteArmorRepairer,
		StructureDroneAugmentorModule,
		StructureRemoteTrackingComputer,
		StructureSensorBooster = 1424,
		StructureRemoteSensorBooster,
		StructureMissileGuidanceComputer,
		StructureRemoteMissileGuidanceComputer,
		StructureDroneNavigationComputer,
		StructureBallisticControlSystem,
		StructureCPUEnhancer,
		StructureRemoteSensorDampener,
		StructureTrackingDisruptors,
		StructureTargetPainter,
		StructureTractorBeam,
		StructureReactorControlUnit,
		StructureRemoteShieldBooster = 1437,
		StructureRemoteHullRepairer,
		StructureRemoteCapacitorTransmitter,
		StructureDroneDamageAmplifier,
		StructureStasisWebifier,
		StructureWarpScrambler,
		StructureTrackingEnhancer,
		StructureGuidanceEnhancer,
		StructureDroneTrackingEnhancer,
		BloodRaiderEventBattleship = 1452,
		BloodRaiderEventFrigate,
		BloodRaiderEventCruiser,
		BloodRaiderEventBattlecruiser,
		UnknownBlueprint = 1461,
		StructureBlueprints,
		StructureModuleBlueprints,
		MissionGenericSupercarrier = 1465,
		StructureAdministrationServiceModuleBlueprint = 1467,
		StructureAdvertisementServiceModuleBlueprint,
		StructureAoEMissileLauncherBlueprint,
		StructureAssemblyServiceModuleBlueprint,
		StructureBallisticControlSystemBlueprint,
		StructureRepulsorFieldBlueprint,
		StructureCitadelServiceModuleBlueprint,
		StructureCPUEnhancerBlueprint,
		StructureDefenseBatteryBlueprint,
		StructureDoomsdayWeaponBlueprint,
		StructureDrillingServiceModuleBlueprint,
		StructureDroneAugmentorModuleBlueprint,
		StructureDroneDamageAmplifierBlueprint,
		StructureDroneTrackingEnhancerBlueprint,
		StructureECMBlueprint,
		StructureEnergyNeutralizerBlueprint,
		StructureGuidanceEnhancerBlueprint,
		StructureMissileGuidanceComputerBlueprint,
		StructureMissileLauncherBlueprint,
		StructureObservatoryServiceModuleBlueprint,
		StructureReactorControlUnitBlueprint = 1488,
		StructureRemoteArmorRepairerBlueprint,
		StructureRemoteCapacitorTransmitterBlueprint,
		StructureRemoteHullRepairerBlueprint,
		StructureRemoteMissileGuidanceComputerBlueprint,
		StructureRemoteSensorBoosterBlueprint,
		StructureRemoteSensorDampenerBlueprint,
		StructureRemoteShieldBoosterBlueprint,
		StructureRemoteTrackingComputerBlueprint,
		StructureResearchServiceModuleBlueprint,
		StructureSensorBoosterBlueprint,
		StructureStargateServiceModuleBlueprint,
		StructureStasisWebifierBlueprint,
		StructureTargetPainterBlueprint,
		StructureTrackingDisruptorBlueprint = 1503,
		StructureTrackingEnhancerBlueprint,
		StructureShipTractorBeamBlueprint,
		StructureWarfareLinkBlueprint,
		StructureWarpDisruptorBlueprint,
		StructureDroneNavigationComputerBlueprint,
		StructureAssemblyRigBlueprint = 1517,
		StructureLaboratoryRigBlueprint = 1520,
		StructureCitadelRigBlueprint,
		StructureDrillingRigBlueprint,
		LogisticsFrigate = 1527,
		Genericgroup1529 = 1529,
		Genericgroup1530,
		MicroJumpFieldGenerators = 1533,
		CommandDestroyers,
		StructureSignalAmplifier,
		StructureSignalAmplifierBlueprint,
		SupportFighter,
		ForceAuxiliary,
		CommandDestroyerBlueprint = 1542,
		MicroJumpFieldGeneratorBlueprint,
		StructureManagement = 1545,
		StructureAntiShipMissile,
		StructureFlakMissile,
		StructureAoEMissile,
		StructureECMscript,
		StructureStasisWebifierScript,
		StructureWarpDisruptorScript,
		StructureResistanceSwitcherScript = 1559,
		StructureFlakLauncher = 1562,
		StructureResistanceSwitcher,
		StructureResistanceSwitcherBlueprint,
		SerpentisEventFrigate = 1566,
		SerpentisEventCruiser,
		SerpentisEventBattlecruiser,
		GuidanceDisruptionScript,
		StructureAssemblyRigMSmallTechIShip,
		StructureAssemblyRigMMediumTechIShip = 1579,
		StructureAssemblyRigMLargeTechIShip,
		StructureAssemblyRigMSmallTechIIShip,
		StructureAssemblyRigMMediumTechIIShip,
		StructureAssemblyRigMLargeTechIIShip,
		StructureAssemblyRigMDrone,
		StructureAssemblyRigMConsumable,
		StructureAssemblyRigMModule,
		StructureAssemblyRigLModule,
		Consumable,
		Drone = 1587,
		StructureAssemblyRigLTechIShip,
		StructureAssemblyRigLTechIIShip,
		StructureAssemblyRigLTechIIComponent,
		StructureAssemblyRigLTechICapitalComponent,
		StructureAssemblyRigLStructureComponent,
		StructureAssemblyRigLSubsystem,
		StructureAssemblyRigXLEquipment,
		StructureAssemblyRigXLShip,
		StructureAssemblyRigXLAllComponents,
		StructureLaboratoryRigMSmallShip = 1598,
		StructureLaboratoryRigMMediumShip,
		StructureLaboratoryRigMLargeShip,
		StructureLaboratoryRigMDrone,
		StructureLaboratoryRigMConsumable,
		StructureLaboratoryRigMModule,
		StructureLaboratoryRigLModuleConsumableDrone,
		StructureLaboratoryRigLShip,
		StructureLaboratoryRigLComponent,
		StructureLaboratoryRigLCapitalComponent,
		StructureLaboratoryRigLStructureComponent,
		StructureLaboratoryRigLSubsystem,
		StructureLaboratoryRigXLEquipment,
		StructureLaboratoryRigXLShip,
		StructureLaboratoryRigXLAllComponents,
		StructureCitadelRigMMissileApplication,
		StructureCitadelRigMMissileProjection,
		StructureCitadelRigMEnergyNeutralizerProjection,
		StructureCitadelRigMEnergyNeutralizerCapReduction,
		StructureCitadelRigMDroneHitpoints,
		StructureCitadelRigMDroneSpeed,
		StructureCitadelRigMEWprojection,
		StructureCitadelRigMEWCapReduction,
		StructureCitadelRigMMaxTargets,
		StructureCitadelRigMSensorResolution,
		StructureCitadelRigMOfficeNumber,
		StructureCitadelRigMJumpCloneNumber,
		StructureCitadelRigMJumpCloneTax,
		StructureCitadelRigMPIproduction,
		StructureCitadelRigMCustomsOfficeTax,
		StructureCitadelRigMLPStorePrice,
		StructureCitadelRigLMissileApplicationandProjection,
		StructureCitadelRigLEnergyNeutralizerProjectionandCapReduction,
		StructureCitadelRigLDroneHitpointsandSpeed,
		StructureCitadelRigLEWProjectionandCapReduction,
		StructureCitadelRigLAoELauncherApplicationandProjection,
		StructureCitadelRigLPointDefenseBatteryApplicationandProjection,
		StructureCitadelRigLMaxTargetsandSensorResolution,
		StructureCitadelRigLOffice,
		JumpCloneandTax = 1636,
		StructureCitadelRigLPI,
		CustomsOfficeTax = 1637,
		StructureCitadelRigLMarketandLPStore,
		StructureCitadelRigXLMissileandAoEMissile,
		StructureCitadelRigXLDroneandPDB,
		StructureCitadelRigXLEnergyNeutralizerandEW,
		StructureCitadelRigXLDoomsdayandTargeting,
		StructureCitadelRigXLOffice,
		JumpClone,
		PI,
		CustomsOffice,
		Market = 1644,
		StructureDrillingRigMReprocessing = 1647,
		StructureDrillingRigLReprocessing,
		StructureDrillingRigXLReprocessing,
		LightFighter = 1652,
		HeavyFighter,
		XXLargeCitadel = 1656,
		MediumCitadel,
		LargeCitadel,
		GuristasEventFrigate = 1664,
		GuristasEventCruiser,
		GuristasEventBattlecruiser,
		GuristasEventBattleship,
		Augmentations = 1670,
		StasisGrappler = 1672,
		InfantryWeapons = 350858,
		InfantryDropsuits = 351064,
		InfantryModules = 351121,
		InfantryVehicles = 351210,
		InfantrySkills = 351648,
		InfantryEquipment = 351844,
		InfantrySkillEnhancers = 354641,
		InfantryInstallations = 354753,
		SurfaceInfrastructure = 364204,
		Services1 = 367487,
		Agents = 367580,
		VisualCustomization = 367594,
		SalvageContainers = 367774,
		SalvageDecryptors = 367776,
		BattleSalvage = 368656,
		Warbarge = 368666,
		InfantryColorSkin = 368726
	}
}
